-- Insert 21 new curated prompts (batch 3)
-- ON CONFLICT DO NOTHING skips existing rows
INSERT INTO public.curated_prompts (id, title, category, user_input, prompt, why_it_works, source, source_creator, source_url, tags)
VALUES
-- #1 Cinematic Action Storyboard (8 panels)
('curated-cinematic-action-storyboard', 'Cinematic Action Movie Storyboard (8 Panels)', 'Storyboards', 'A cinematic action movie storyboard with a female protagonist winning a fight', 'Create a high-quality 4K cinematic action movie storyboard with EXACTLY 8 PANELS ONLY (no more, no less), showing a female protagonist in a realistic fight sequence where she wins. Use dramatic lighting, high contrast shadows, realistic environments (abandoned warehouse, rooftop, or underground fight arena), and a gritty film tone. No text anywhere. The storyboard must include exactly these 8 scenes: Wide establishing shot of a dark, intense location (rain, dust, or low light atmosphere), both fighters facing each other. Close-up of the woman''s focused expression, controlled breathing, tension building. Opponent attacks first with aggressive movement (punch or kick). She narrowly dodges — dynamic motion, fast reaction, camera tracking. Close combat exchange — blocks, counters, and impact moments with cinematic slow motion. Turning point — she reads the opponent and lands a clean, powerful counter move. Decisive takedown — opponent falls hard, dramatic impact, environment reacting (dust, water splash, etc.). Final frame — she stands strong and calm, slightly injured but dominant, looking forward under dramatic lighting, clear victory. Use varied camera angles (wide, close-up, over-shoulder, low angle), realistic fight choreography, motion blur, and physical impact details. Tone should feel like a Hollywood action film, focusing on tension, realism, and character strength — not stylized or social media aesthetic. Strict rule: only 8 panels, no repetition, no extra frames.', 'The EXACT 8 PANELS constraint forces a tight narrative arc (setup → conflict → resolution). Each panel has a specific camera angle and emotional beat prescribed, preventing generic repetition. The "no text anywhere" rule keeps focus on visual storytelling. Hollywood-action tone anchor ensures gritty realism over anime/comic style.', 'curated', NULL, NULL, ARRAY['storyboard','action','cinematic','fight']::text[]),

-- #2 CCTV Surveillance Footage
('curated-cctv-surveillance-footage', 'CCTV Surveillance Footage With AI Overlay', 'Cinematic', 'Photorealistic CCTV surveillance footage of a woman being tracked in a crowd', 'Photorealistic CCTV surveillance footage, high-angle overhead view of a crowded urban street. An Asian woman centered, walking forward, looking up at the camera with a warm, confident smile. Surrounding pedestrians heavily motion-blurred, subject in sharp focus. Black and white monochrome, high contrast, cinematic lighting. Advanced AI facial recognition interface overlay: green bounding box labeled "PERSON OF INTEREST", connected side panel with zoomed face portrait and data — SUBJECT ID: 01, STATUS: TRACKED, GAZE: UP, CONFIDENCE: 86%. Timestamp and REC indicator visible. Grainy texture, digital noise, compression artifacts, subtle scan lines. Slight lens distortion, documentary-style realism, dynamic composition.', 'The CCTV aesthetic (high-angle, monochrome, grain, compression artifacts) is a complete visual language GPT Image 2 renders accurately. The AI overlay (bounding box, data panel, confidence %) adds a sci-fi surveillance layer. Motion-blurring the crowd while keeping the subject sharp creates instant focal hierarchy.', 'curated', NULL, NULL, ARRAY['cinematic','surveillance','monochrome','ai-overlay']::text[]),

-- #3 Date Night Cinematic Series (Image Edit - needs reference photo)
('curated-date-night-series', 'Date Night Cinematic Series (3 Scenes)', 'Image Edits', NULL, 'Using the attached reference photo of the couple as the exact characters, generate a cinematic Date Night series of 3 high-quality, photorealistic images in a dramatic, romantic, movie-poster style. Scene 1 – Dinner Time: The couple dressed elegantly for a romantic dinner at a top luxury restaurant in NYC. She is wearing a stunning, floor-length deep burgundy evening gown with subtle sparkle and elegant jewelry. He is wearing a tailored black designer suit with a black shirt and no tie, looking sharp and sophisticated. They are seated at a beautifully set candlelit table with city views in the background. Warm ambient lighting, romantic atmosphere. Large elegant text overlay at the bottom: "Dinner Time." Scene 2 – Dance the Night Away: The couple at an upscale, vibrant NYC nightclub. She is wearing a sexy, short sparkling black cocktail dress with heels. He is wearing a stylish black button-up shirt with the top buttons open, sleek black trousers, and a modern blazer. They are dancing closely on the dance floor with colorful club lights, lasers, and a lively crowd behind them. Large stylish text overlay at the bottom: "Dance the night away." Scene 3 – Netflix and Chill: The couple in a luxurious NYC hotel suite, relaxing on a big comfortable bed. Both are in cozy, matching luxury pajamas. They are cuddling under a blanket, smiling and laughing while watching Netflix on a large TV. Soft warm lighting from lamps and the TV glow. Large playful text overlay at the bottom: "Netflix and Chill." Maintain the exact likeness of the couple from the reference photo in all three images. Cinematic lighting, ultra-realistic details, 8K quality, romantic and stylish mood throughout.', 'Multi-scene consistency prompt using a reference photo as the identity anchor. Each scene has distinct wardrobe, lighting, and mood while maintaining character likeness. Text overlays label each scene for a movie-poster series feel. The progression (formal → energetic → intimate) tells a complete narrative.', 'curated', NULL, NULL, ARRAY['image-edit','series','cinematic','romance']::text[]),

-- #4 Travel Infographic Guide
('curated-travel-infographic-guide', 'Premium Travel Guide Infographic', 'Infographics', 'Create a detailed travel guide infographic for a country', 'Create a detailed, highly engaging infographic-style travel guide for [COUNTRY]. The output should feel like a premium designer travel poster mixed with a fun comic illustration. Include: A catchy title and short subtitle. What to see (specific places, not generic). What to eat (local dishes, real names, not "street food"). What to do (mix of tourist + local + unique experiences). Local vibe (culture, behavior, atmosphere). Quick practical tips (transport, budget, mistakes to avoid).', 'The instruction to avoid generic terms ("not street food") forces specific, authentic content. Combining "premium designer travel poster" with "fun comic illustration" creates an unusual hybrid that stands out from typical travel infographics. The five sections (see, eat, do, vibe, tips) ensure comprehensive coverage without being overwhelming.', 'curated', NULL, NULL, ARRAY['infographic','travel','guide','template']::text[]),

-- #5 Luxury Perfume Advertisement
('curated-luxury-perfume-ad', 'Ultra-Luxury Perfume Advertisement', 'Posters', 'A luxury Dior perfume advertisement with cinematic studio lighting', 'Ultra-luxury perfume advertisement, cinematic studio lighting, deep red monochrome aesthetic. A beautiful elegant East Asian woman with smooth glowing skin and soft makeup, loose wavy brown hair, wearing a red silky satin shirt with soft folds and glossy highlights. She is holding a perfume bottle close to her face with a delicate grip. Bottle is crystal clear with soft pink liquid, reflective glass, metallic cap, luxury finish, subtle glow and light reflections. Composition: Close-up portrait, chest-up framing. Model slightly tilted head, soft confident expression. Sharp focus on face + perfume bottle. Background: rich deep red silk fabric waves, soft gradients, luxury feel. Lighting: Warm cinematic key light from front. Soft rim light from side for glow. Subtle specular highlights on skin and satin shirt. High-end beauty retouch look. Foreground elements: Dark marble table surface, red roses, petals scattered, glass candle with warm flame, ribbon placed casually. Text layout (minimal luxury style): Top left brand name in elegant serif font. Below: thin gold line icons with descriptors — Timeless Elegance, Exquisite Scent, Long Lasting Fragrance, Iconic Design. Color palette: Deep red, burgundy, gold accents, warm skin tones. Style: ultra realistic, 8k, fashion photography, luxury branding, glossy finish, cinematic, high contrast, premium aesthetic, shallow depth of field.', 'The structured sections (Composition, Lighting, Foreground, Text layout, Color palette) give GPT Image 2 clear hierarchical instructions for a complex commercial scene. Specifying exact foreground props (marble, roses, candle, ribbon) prevents empty negative space. The monochrome red palette creates cohesive luxury branding.', 'curated', NULL, NULL, ARRAY['poster','luxury','advertisement','fashion']::text[]),

-- #6 3D Food Advertisement
('curated-3d-food-ad-chibi', '3D Food Ad With Chibi Characters', 'Posters', 'Adorable 3D food advertisement with tiny chibi characters interacting with oversized food', 'Adorable 3D food advertisement scene featuring a delicious oversized sandwich / cheesy snack placed on a clean pastel platform, surrounded by tiny chibi-style children interacting with the food (climbing ladders, sitting on top, eating, celebrating). Soft rounded design, playful storytelling composition. Creamy melted cheese, fresh ingredients, glossy textures, ultra-detailed food realism. Mini characters with Pixar-style proportions, expressive faces, soft 3D rendering. Pastel green and warm beige background with smooth gradients, minimal aesthetic props (balls, shapes). Floating speech bubbles with cute text. Big soft 3D typography headline at the top in a rounded, inflated style. Soft studio lighting, subtle shadows, cozy and cheerful mood, high-end commercial food poster, ultra-clean, 4K.', 'Scale contrast (tiny characters vs oversized food) creates instant visual interest and playful storytelling. Pixar-style proportions anchor the 3D character style precisely. The combination of ultra-realistic food textures with stylized characters is a proven commercial advertising technique.', 'curated', NULL, NULL, ARRAY['poster','3d','food','chibi','advertisement']::text[]),

-- #7 Pinterest Doodle Aesthetic (Image Edit)
('curated-pinterest-doodle-aesthetic', 'Pinterest/Xiaohongshu Doodle Aesthetic Edit', 'Image Edits', NULL, 'Edit this photo into a cute Pinterest/Xiaohongshu-style doodle aesthetic edit while keeping the original composition and colors natural. Do NOT heavily change the original lighting or color grading. Keep the tones soft, airy, warm, and realistic. Avoid oversaturated colors, HDR effects, strong orange filters, or excessive contrast. Add hand-drawn doodle elements around the main objects: white outline strokes, sketchy sparkles, stars, hearts, arrows, tiny flowers, playful swirls, mini handwritten notes. Add small cute mascot-style doodles that match the vibe of the photo (tiny bear, smiling drink, cute food character, sleepy cloud, etc.) but keep them subtle and balanced. Use handwritten white text with short relatable captions only. Do NOT add too many words or overcrowd the image. Around the image, add several mini chibi (3D cute style) versions of the character, while maintaining the original facial features. Chibi characters have various poses and expressions: jumping cheerfully, waving, sitting relaxed, holding a drink, cute and playful expressions. Add hand-drawn white doodle elements: outline around the main body, stars, hearts, sparkles, motion lines, small cute icons. Add aesthetic handwriting such as: "shine," "bright day," "happy," "smile," etc. (casual doodle font). Overall style: clean and aesthetic composition, white sticker outline, soft pastel color tone, high detail 3D chibi, glossy look, cute Korean aesthetic.', 'Layered editing instructions: preserve original → add doodles → add chibi versions → add text. The strong negative constraints ("Do NOT heavily change lighting") prevent the common AI failure of over-processing the base image. The Pinterest/Xiaohongshu reference anchors a specific, popular aesthetic.', 'curated', NULL, NULL, ARRAY['image-edit','doodle','aesthetic','korean']::text[]),

-- #8 Food Doodle Fusion (3 variants)
('curated-food-doodle-fusion', 'Food + Doodle Fusion Photography', 'Image Edits', NULL, 'A top-down photo of a colorful homemade meal on a plate, styled in natural lighting. Add whimsical hand-drawn doodles interacting with the food — expressive faces, motion lines, arrows, and tiny illustrated characters. Include fun, original handwritten annotations describing textures and emotions (e.g., "crisp bites," "flavor party," "happy crunch"). Use a mix of curved text, sparkles, and playful icons around the plate. Keep the doodles integrated naturally with the food, giving it a lively, storytelling feel. Warm, cozy aesthetic, social media friendly, highly detailed. Variant 2: A realistic breakfast scene photographed from above, featuring eggs, toast, and fresh sides. Overlay creative sketch-style illustrations that bring the food to life — smiling elements, animated swirls, steam lines, and dynamic highlights. Add unique handwritten captions and labels in a fun, casual font. Variant 3: A close-up of a comforting dish with cinematic lighting and rich textures. Layer artistic doodles that exaggerate movement and flavor — spirals, bursts, mini characters, and expressive symbols. Include creative text phrases describing the experience (e.g., "twirl magic," "flavor swirl," "bite bliss"). Use varied line thickness and playful composition, blending illustration with realism.', 'The doodle-on-food hybrid creates shareable social media content. Specifying that doodles should "interact with the food" (not just overlay) ensures integration. Three variants show progression from warm/cozy to cinematic, demonstrating the technique''s flexibility.', 'curated', NULL, NULL, ARRAY['image-edit','food','doodle','social-media']::text[]),

-- #9 Anime Character Design Sheet
('curated-anime-character-design-sheet', 'Anime Character Design Setting Materials', 'Open-Ended Creative', 'Create original anime character setting materials based on a worldview with bureaucratic magic administration', 'Based on the worldview of a city-state where magic is deeply embedded in administration, taxation, and licensing systems (magic requires a permit, illegal magic is subject to seizure), create an image in the style of original anime character setting materials. Three characters: Tax Collector, Magic Audit Clerk, Sealed Item Transporter. Overall atmosphere: Serene, intellectual, slightly cold, orderly, imposing. Design costumes driven primarily by the worldview — express personalities through clothing, gear, materials, structure, color schemes, silhouettes, and cultural symbols. Silhouettes should be linear and rigid, emphasizing uniforms, clerical work, auditing tools, and seal management. Welcome structures where clothes look like "ledgers, envelopes, forms, permits, seal labels." Color schemes centered on black, gray, sooty tones, white, and deep vermilion. Image presentation: High resolution, anime style, delicate line art, clean cel-shading, official setting materials collection or concept art sheet style. Full-body standing pose. Include small costume detail diagrams or gear diagrams. Layout: administrative/institutional — linear, organized, like forms or spec sheets. Make costumes that only work because of this world — not mass-produced fantasy.', 'The extensive worldbuilding context (magic-as-bureaucracy) gives the AI a unique design constraint space. The forced differentiation rules (no generic robes, no RPG tropes, costumes must look like "ledgers and permits") prevent default anime aesthetics. The character-sheet format with detail diagrams is a specific deliverable type the model handles well.', 'curated', NULL, NULL, ARRAY['anime','character-design','concept-art','worldbuilding']::text[]),

-- #10 Graduation Silhouette Narrative Poster
('curated-graduation-silhouette-poster', 'Graduation Silhouette Narrative Poster', 'Posters', 'Generate a collectible narrative poster based on my graduation photo with double-exposure style', 'Automatically generate a collectible epic narrative poster based on my character portrait (graduation photo): a massive side-profile silhouette of me as the outer contour, with the interior of the silhouette organically growing into a complete worldview — iconic scenes, character relationships, symbolic icons, key architecture, creatures, props, and atmosphere that best fit the theme (campus + graduation). Overall, it''s not a regular collage, but a sophisticated silhouette-contour-filled narrative composite, with double-exposure-style associations, leaning more toward a fusion of movie poster and dreamy watercolor illustration grid; soft aerial perspective, lightly fogged waves, paper grain, white edges and brush marks, large areas of negative space, restrained high-end layout, quiet, grand, sacred, nostalgic, poetic, legendary vibe. Style, color, scenes, and materials all auto-adapt to the theme, with all elements strongly tied to it for instant recognition — no clutter, no forced collage, no templated backgrounds, no cheap fantasy assets. Use English fonts if any.', 'The "silhouette as container for narrative world" concept is a specific double-exposure technique. Strong negative constraints ("no clutter, no forced collage, no templated backgrounds") prevent the generic collage trap. The mood vocabulary (quiet, grand, sacred, nostalgic, poetic, legendary) is precise enough to control tone without being prescriptive about content.', 'curated', NULL, NULL, ARRAY['poster','double-exposure','graduation','narrative']::text[]),

-- #11 Isometric Movie Scene Diorama
('curated-isometric-movie-diorama', 'Isometric Movie Scene Diorama', 'Open-Ended Creative', 'Create a 45-degree isometric miniature diorama of an iconic movie scene', 'Present a clear, 45-degree top-down isometric miniature 3D cartoon scene of the iconic scene [SCENE NAME] from [MOVIE/SHOW], with soft refined textures, realistic PBR materials, and gentle lifelike lighting. Create a small raised diorama-style base that includes the most recognizable elements of this scene, along with tiny stylized characters if needed (no facial details). Use a clean solid [BACKGROUND COLOR] background. At the top-center, display "MOVIE/SHOW" in large bold text, directly beneath it show [SCENE NAME] in medium text, and place the official logo associated with [MOVIE/SHOW] below the subtext. All text must automatically match the background contrast (white or black). Composition: perfectly centered layout, square 1080x1080, ultra-clean, high-clarity diorama aesthetic.', 'Template-based prompt with clear [PLACEHOLDERS] makes it reusable for any movie/show. The PBR materials + gentle lighting combination creates a premium collectible-figure aesthetic. "No facial details" on tiny characters avoids uncanny-valley issues at small scale. The text hierarchy (title → scene → logo) is a complete branding system.', 'curated', NULL, NULL, ARRAY['isometric','diorama','movie','3d','template']::text[]),

-- #12 Brand Identity System Poster
('curated-brand-identity-system', 'Agency-Grade Brand Identity System Poster', 'Infographics', 'Upload a logo and construct a complete brand identity system poster', 'Upload a logo. From it, construct a complete, investment-worthy brand identity system poster — the kind that closes client deals and dominates Behance front pages. Prime directive: Every element — color, tone, shape, texture, personality — must be extracted directly from the uploaded logo. Nothing generic. Nothing templated. Format: Vertical, 4:5 aspect ratio, multi-column grid, layered and dense with zero wasted space. Sections: (1) Brand Header — brand name in commanding typography, 6-word max brand statement, three soul descriptors. (2) Color System — primary 3-5 colors extracted from logo, secondary 3-5 supporting colors, accent hit colors, each with wide swatch, HEX code, and role label. Include gradient blends and light/dark mode behavior. (3) Typography System — headline, subheadline, body tiers with example text showing undeniable hierarchy. (4) Visual Language — image style, lighting quality, texture references, 3-5 art-directed mood board tiles. (5) Brand Applications — product packaging, website hero, mobile app screen, social media posts, business card, out-of-home ad — every mockup same DNA. (6) Design System — buttons, cards, input fields, navigation bar, spacing scale. (7) Iconography — 6-10 icons in same visual grammar as logo.', 'This is a complete design-agency deliverable compressed into a single prompt. The "extracted from the uploaded logo" constraint ensures coherence. The 7-section structure mirrors actual brand guidelines documents. Specifying "the kind that closes client deals" sets a quality bar the model understands.', 'curated', NULL, NULL, ARRAY['infographic','branding','identity','design-system']::text[]),

-- #13 Korean-Style Character Illustration
('curated-korean-style-illustration', 'Korean-Style Character Illustration', 'Open-Ended Creative', 'Create a Korean-style illustration with expressive character design and doodle elements', 'Create an illustration of a character: Korean-style illustration, with a distinct and memorable character design, natural and expressive facial emotions, half-body composition, and a dynamic pose. The clothing should feature intricate, refined details. Use a hand-drawn doodle style with ink splashes, loose and spontaneous linework, and a mix of pastel tones with ink shading. Aim for a comic sketch texture. Keep the background minimal and white, with symbolic decorative elements scattered around the character. The overall atmosphere should be strong and evocative, with high detail and high quality.', 'The combination of "Korean-style illustration" + "hand-drawn doodle" + "ink splashes" creates a specific aesthetic that blends precision with spontaneity. Specifying "half-body composition" and "dynamic pose" prevents the static full-body default. The "white background with scattered symbolic elements" instruction creates clean, social-media-ready output.', 'curated', NULL, NULL, ARRAY['illustration','korean','character','doodle']::text[]),

-- #14 Designer's Mind Illustration (Image Edit)
('curated-designers-mind-illustration', 'Inside a Designer''s Mind Illustration', 'Image Edits', NULL, 'Create a stylish illustration themed around "Inside a Designer''s Mind." An illustration where, next to the side profile of the woman from the attached image, 3D elements of Illustrator, Photoshop, Canva, color palettes, and other designer-related parts overflow from her head. Colors that match the vibe of Substack articles. Aspect ratio is 16:9.', 'The "overflow from head" concept is a specific illustration trope (thoughts-becoming-visual) that GPT Image 2 handles well. Mixing 2D profile with 3D software elements creates visual interest. The "Substack article vibe" color anchor is unusual but effective for muted, editorial tones.', 'curated', NULL, NULL, ARRAY['image-edit','illustration','designer','creative']::text[]),

-- #15 iPhone Candid Self-Portrait
('curated-iphone-candid-self-portrait', 'iPhone Candid Everyday Snapshot', 'Cinematic', 'Draw a snapshot of your everyday life as if accidentally taken on an iPhone', 'I want to see what you really look like. Draw a snapshot of your everyday life as if it were accidentally taken on an iPhone. Make it feel like a very ordinary, imperfect candid shot. The photo should have slight motion blur, with uneven, natural lighting.', 'The meta-prompt ("I want to see what you really look like") triggers an interesting creative interpretation. "Accidentally taken" + "imperfect candid" + "slight motion blur" + "uneven natural lighting" combine to defeat the AI''s perfection bias. Extremely short but effective.', 'curated', NULL, NULL, ARRAY['cinematic','candid','iphone','everyday']::text[]),

-- #16 Mecha Techwear Fashion Poster
('curated-mecha-techwear-poster', 'Mecha Techwear Fashion Poster', 'Posters', 'A high-quality editorial fashion poster with mecha-inspired techwear', 'A high-quality 8K editorial fashion poster featuring a female model in ultra-detailed Mecha-inspired techwear. She is standing in a confident pose in front of a massive, glowing [COLOR] robotic mecha suit. The outfit includes a technical tactical jacket with metallic panels, joggers with utility straps, and chunky mecha-style sneakers. Dramatic cinematic lighting with particles and embers in the air. The background is a dark, industrial void. Overlay the image with futuristic UI elements, HUD graphics, bold typography like "MYTHODE" and technical specifications. Muted color palette with sharp [COLOR] accents, film grain, and high contrast. Aspect ratio 2:3.', 'The fashion-meets-mecha concept creates a unique editorial aesthetic. Layering UI/HUD graphics over a fashion shot is a modern poster technique. The [COLOR] placeholder makes this reusable. Film grain + high contrast + particles create atmosphere without complex scene descriptions.', 'curated', NULL, NULL, ARRAY['poster','fashion','mecha','techwear']::text[]),

-- #17 Zine-Style Food Infographic (3 pages)
('curated-zine-food-infographic', 'Zine-Style Food Infographic (3-Page Spread)', 'Infographics', 'Create a vibrant 3-page zine-style infographic about a famous fast-food item', 'Create a vibrant, colorful 3-page zine-style infographic about a famous fast-food item: "KFC Original Recipe Fried Chicken." Style: mixed media collage combining realistic crispy fried chicken photography, bold graphic elements, halftone textures, retro fast-food ads, doodles, stickers, and playful handwritten typography. Color palette inspired by red, white, and warm golden tones. Energetic, slightly retro American fast-food vibe. Layout: Three vertical panels side-by-side (like an open zine spread). PAGE 1 (left): Big bold title, subtitle "crispy - juicy - legendary", large hero image, sections for "What Makes It Famous?" and "Why People Love It", flavor diagram (salty, savory, crispy, juicy). PAGE 2 (center): "How It''s Made (Inspired Version)" — ingredients list with icons, step-by-step visuals with arrows, crispy texture highlights, steam effects, "secret spice blend" graphic. PAGE 3 (right): "Global Craze & Variations" — bucket/sandwich/wrap visuals, variations list, "Why It Works" analysis, fun fact, bold handwritten closing quote. Design details: Hand-drawn arrows, stars, flames, crunchy texture doodles, retro stickers, paper textures, bold labels, slight grunge texture. High resolution, dynamic and playful composition. Aspect ratio: wide horizontal (3-panel layout).', 'The 3-page zine format is a specific editorial structure. Mixed-media collage (photo + illustration + typography) creates visual richness. Each page has a distinct purpose (hero/intro → process → variations) preventing repetition. The retro fast-food aesthetic is a strong, well-defined style anchor.', 'curated', NULL, NULL, ARRAY['infographic','zine','food','collage']::text[]),

-- #18 Botanical Painting Conversion (Image Edit)
('curated-botanical-painting-conversion', 'Botanical Painting Style Conversion', 'Image Edits', NULL, 'Please convert this illustration into a botanical painting style on canvas, drawn with plant dyes (leaves, stems, flowers, fruits, roots, etc.). Emphasize an organic expression that leverages the soft bleeding of natural dyes, gentle color variations, and the texture of the canvas. Prioritize subdued earth tones and pale gradations derived from plants, rather than chemical vibrancy, to create a warm, serene, and poetic botanical atmosphere. Do not depict the plants used themselves. Fully preserve the original illustration''s composition and characters.', 'The "plant dyes on canvas" instruction is a highly specific medium that produces a unique aesthetic — soft bleeding, gentle color variations, canvas texture. The constraint "do not depict the plants used themselves" prevents literal interpretation. "Fully preserve composition and characters" ensures the edit is a style transfer, not a reimagining.', 'curated', NULL, NULL, ARRAY['image-edit','botanical','painting','style-transfer']::text[]),

-- #19 Naruto Propaganda Poster
('curated-naruto-propaganda-poster', 'Anime Propaganda Poster (Double Exposure)', 'Posters', 'Create a propaganda-style artistic poster of an anime character with double exposure and collage elements', 'Create an iconic propaganda-style artistic reinterpretation poster. Composition: Top section has a large iconic visual of the character''s head, facial features, mask-like framing or half-body silhouette as dominant symbolic focal point. Middle to bottom section has full-body character in stable stance or light dynamic motion as secondary narrative subject. Layout: hierarchical visual composition, center-weighted with left-right narrative tension, A4 vertical poster format. Visual style: double exposure, narrative collage, layered visual storytelling. Background layers include cloud textures, ink wash effects, white negative space fields, environmental backgrounds. Collage elements include secondary character fragments, action micro-scenes, symbolic objects, environment overlays. Aesthetic: poetic Eastern tone, ink diffusion edges, soft blur transitions, visual fragmentation effects, pop vibrant striking contrast colors, premium cinematic refined quality. Composition flow: vertical flowing visual path connecting top silhouette, collage layers, and full character. Design principles: high negative space usage, strong visual hierarchy, narrative depth through layering, poster-series visual language, strong focal impact.', 'The hierarchical composition (head silhouette top → full body bottom) creates a propaganda-poster power structure. Double exposure + narrative collage + ink wash blends Eastern and Western poster traditions. The structured JSON-like format of the original translates into clear AI instructions for each visual layer.', 'curated', NULL, NULL, ARRAY['poster','propaganda','anime','double-exposure']::text[]),

-- #20 Game Boy Exploded View
('curated-gameboy-exploded-view', 'Game Boy Exploded View (Vintage)', 'Infographics', 'Exploded view of a Game Boy with vintage sepia filter', 'Exploded view of a Game Boy, with a vintage, sepia-toned filter, components appearing aged and slightly worn, set against a backdrop of old blueprints, nostalgic feel, retro illustration.', 'Extremely concise but effective. "Exploded view" is a specific technical illustration format. The vintage/sepia/aged treatment transforms a technical diagram into nostalgic art. "Old blueprints" backdrop adds contextual richness without complexity.', 'curated', NULL, NULL, ARRAY['infographic','exploded-view','retro','gaming']::text[]),

-- #21 Scientific Research Infographic Poster
('curated-scientific-research-infographic', 'Scientific Research Paper Infographic', 'Infographics', 'Create a corporate-style scientific infographic poster for a research paper', 'Create a high-end, editorial, corporate-style scientific infographic poster (portrait, A1 ratio) that communicates a research paper with structured clarity, data storytelling emphasis, and report-style visual hierarchy. Feel like a hybrid of corporate research report (McKinsey/Deloitte), clean business infographic, and analytical dashboard. Content interpretation: identify primary contribution type (algorithm, model, framework, empirical study, system), classify dominant structure (pipeline, hierarchical, modular, iterative, comparative, etc.), define core idea in 1-2 sentences, allocate visual priority (40% core insight, 30% mechanism, 20% results, 10% context). Visual system: editorial report style, warm beige background (#F4F1EC), text colors (#111111 primary, #4A4A4A secondary, #7A7A7A annotations), accent soft cyan (#73C8E0) for highlights, black for emphasis, beige-gray (#D9D3C7) for neutral segments. Layout: 2-3 column editorial grid, modular sections. Header with title (bold, large), subtitle, authors top-left; "THE QUESTION" and "THE ANSWER" top-right. Section flow: Overview → Core insight (numbers + diagram) → Mechanism → Data/results → Supporting insights → Conclusions. Data visualization: horizontal bar charts preferred, no gridlines, minimal axes, direct labeling, max 2-3 charts per section. Typography hierarchy: title bold large, section headers uppercase spaced, numbers very large and dominant, body short and compact. Footer with citation and source.', 'This is a complete design system specification compressed into a prompt. The specific hex codes, visual priority percentages (40/30/20/10), and color role assignments give GPT Image 2 precise constraints. The McKinsey/Deloitte reference anchors the corporate aesthetic. The content interpretation layer forces the AI to analyze before designing.', 'curated', NULL, NULL, ARRAY['infographic','scientific','research','corporate']::text[])

ON CONFLICT (id) DO NOTHING;
