-- Insert 50 new curated prompts (batch 2)
-- ON CONFLICT DO NOTHING skips existing rows
INSERT INTO public.curated_prompts (id, title, category, user_input, prompt, why_it_works, source, source_creator, source_url, tags)
VALUES
-- #1 Aerial Photography
('curated-aerial-sf-manhattan', 'Aerial Photo of San Francisco and Manhattan', 'Cinematic', 'Just a random aerial photo of San Francisco and Manhattan', 'Just a random aerial photo of San Francisco and Manhattan', 'Demonstrates that GPT Image 2 can produce convincing drone-style aerial city photography from an extremely short prompt. The casual phrasing ("just a random") triggers natural, unposed composition.', 'curated', NULL, NULL, ARRAY['aerial','city','photography']::text[]),

-- #2 Chibi Clone Handaccount Photo (Image Edit - needs uploaded photo)
('curated-chibi-clone-handaccount', 'Chibi Clone Handaccount Photo', 'Image Edits', NULL, 'Please create a high-quality "Chibi Clone Handaccount Photo / Chibi Sticker Diary Photo" based on the real-life photo uploaded by the user. 【Core Task】 Image A is the authentic photo uploaded by the user. On the basis of preserving the main subject and original scene of the photo as much as possible, perform "Chibi Clone Handaccount Enhancement" on the entire image. Please retain the real person, facial features, hairstyle, hair color, clothing, body proportions, pose, lighting, and background environment from the original photo. Do not swap faces, do not significantly alter the person''s identity, do not over-beautify, do not turn the real subject into an illustration, and do not destroy the authentic photographic feel of the original image. 【Chibi Clone Characters】 Add 5–8 Chibi mini clones (chibi-style mini versions) of the same person around the real subject. These Chibi clones must be cute mini versions evolved from the real protagonist''s image, retaining the person''s hairstyle, hair color, clothing colors, accessories, temperament, and main physical features. Chibi character style: cute chibi / kawaii sticker style, big head small body, big eyes, rich expressions, cute and lively actions, exquisite like digital stickers, unified style. 【Sticker Presentation Method】 These Chibi clones should appear like cute stickers pasted onto the photo, distributed around the person. Each clone can feature white outlines, soft shadows, slight floating effect, sticker-like edges. 【Hand-Drawn Doodle Elements】 Add hand-drawn doodle elements: hearts, stars, sparkles, arrows, speech bubbles. Colors primarily white, supplemented with pink. 【Handwritten Copy】 Add 5–8 short handwritten-style phrases around the frame based on the photo''s theme. 【Overall Style Keywords】 realistic photo enhancement, chibi mini versions, kawaii sticker style, scrapbook doodles, handwritten notes, lifestyle diary aesthetic, playful and polished, soft lighting, cute but clean, high detail, social-media-friendly.', 'Structured image-edit prompt with layered instructions: preserve identity → add chibi clones → sticker presentation → doodle elements → handwritten text. Each section has explicit constraints preventing common failures (face swap, identity loss, inconsistent style).', 'curated', NULL, NULL, ARRAY['image-edit','chibi','sticker','scrapbook']::text[]),

-- #3 Aerial Winter Cabin
('curated-aerial-winter-cabin', 'Aerial Winter Cabin in Snowy Forest', 'Cinematic', 'A cinematic aerial photo of a yellow wooden cabin in a snowy coniferous forest with moody winter atmosphere', 'A cinematic high-angle aerial photograph of a tiny vibrant yellow wooden cabin with a thick snow-covered roof sitting silently beside a winding snowy path in the heart of a dense coniferous forest. Every towering pine tree is heavily draped in frost and white powder, creating a lush texture that stretches across the entire frame under a moody and diffuse winter sky. The scene is immersed in a cool monochromatic color grade of deep teal and slate blue which enhances the mystical and serene atmosphere of the frozen wilderness. The lighting is soft and ethereal with a gentle morning fog blurring the distant trees, captured in sharp resolution with a focus on the delicate crystalline details of the snow and the weathered wood grain of the cabin.', 'High-angle aerial perspective with a single warm-colored subject (yellow cabin) against a monochromatic cool environment creates immediate focal point. The teal/slate blue color grade and "diffuse winter sky" instructions control mood precisely.', 'curated', NULL, NULL, ARRAY['aerial','winter','cabin','landscape']::text[]),

-- #4 Aerial Ice Canyon
('curated-aerial-ice-canyon', 'Aerial Ice Canyon With Lone Tree', 'Cinematic', 'A top-down aerial view of an ice canyon with a single yellow tree on a rocky ledge', 'A top-down aerial 3D render of a deep jagged ice canyon carving through a vast frozen arctic landscape with a single vibrant yellow tree standing on a rocky ledge. The intricate geological layers of the dark stone and blue ice walls are captured with extreme detail and sharp displacement mapping while soft diffuse sunlight creates deep shadows within the crevice. The surrounding environment is a sea of pristine white snow and frosted tundra textures under a cold cinematic color grade of icy blues and brilliant whites. Every needle on the evergreen tree and every crack in the frozen ground is rendered in high resolution with professional render fidelity and a peaceful yet rugged atmosphere.', 'Top-down perspective with extreme scale contrast (tiny tree vs massive canyon) creates visual drama. Specifying geological layers, displacement mapping, and surface textures adds dimensional depth to what could be a flat aerial shot.', 'curated', NULL, NULL, ARRAY['aerial','arctic','canyon','3d-render']::text[]),

-- #5 Aerial Icebreaker Ship
('curated-aerial-icebreaker', 'Aerial Icebreaker Ship in Arctic Sea', 'Cinematic', 'Top-down aerial photo of an icebreaker ship cutting through frozen sea ice', 'A top-down aerial drone photograph of a powerful industrial icebreaker ship with a vibrant yellow deck and white bridge as it carves a path through a frozen arctic sea. The composition is perfectly vertical and symmetrical, showing the vessel splitting massive jagged plates of white sea ice to reveal the deep charcoal frigid water beneath. A trail of crushed ice fragments and a churning wake follow the ship, while the soft golden hour sunlight casts long shadows across the deck and illuminates the crystalline textures of the surrounding frozen landscape. The image is captured with a high-end wide-angle lens in photorealistic resolution, featuring a cinematic color grade that emphasizes the contrast between the bold machinery and the cold monochromatic tones of the winter environment.', 'Perfect symmetry instruction creates satisfying composition. The contrast between warm yellow deck and cold ice palette, plus the ship''s wake revealing dark water, adds strong visual tension. Golden hour light on an arctic scene is an unusual pairing that elevates the result.', 'curated', NULL, NULL, ARRAY['aerial','ship','arctic','symmetry']::text[]),

-- #6 Aerial Car in Snow Forest
('curated-aerial-car-snow-forest', 'Aerial Car on Snowy Forest Road', 'Cinematic', 'Top-down aerial of a yellow car driving on a straight road through snowy pine forest', 'A cinematic top-down aerial drone photograph of a solitary vibrant yellow car driving along a straight vertical asphalt road that cuts through a dense snow-covered pine forest. The composition is perfectly symmetrical with thousands of frosted evergreen trees lining both sides of the path, fading into a thick ethereal blue mist in the far distance. The scene is captured with diffuse overcast lighting that eliminates harsh shadows and emphasizes the cold teal and white color palette of the winter landscape. Every needle on the trees is rendered with crisp high-definition detail, creating a sharp contrast against the smooth gray road and the glossy finish of the vehicle, resulting in a photorealistic masterpiece with a moody and serene atmospheric quality.', 'Perfect symmetry + leading lines (road vanishing into mist) + single warm subject (yellow car) against cold monochrome = guaranteed visual impact. The "diffuse overcast lighting" instruction prevents harsh shadows that would break the ethereal mood.', 'curated', NULL, NULL, ARRAY['aerial','car','forest','symmetry']::text[]),

-- #7 Visual Prompt Anatomy Template (Generic)
('curated-prompt-anatomy-generic', 'Visual Prompt Anatomy Template', 'Infographics', 'Create a visual prompt anatomy template that breaks down a prompt into functional building blocks', 'Create a premium, visually structured Visual Prompt Anatomy Template for [PROMPT NAME / USE CASE]. The goal is to break down a prompt into clear functional building blocks so a viewer can instantly understand how the prompt is constructed, why each part matters, and how the structure influences the final output. This visual should feel like a premium educational design board, prompt engineering explainer, or strategy sheet. Prompt anatomy structure: Break the prompt into functional sections such as role/identity assignment, task definition, context block, input variables, output format instructions, style/tone instructions, constraints and rules, examples, reasoning guidance, evaluation criteria, fallback behavior. For each block include: block name, short explanation, what it controls, why it matters, visual marker/connector/label. Include: clear title, visual segmentation, arrows/labels/callouts/connectors, readable hierarchy showing flow from instruction to result, clear distinction between core and optional blocks. Art direction: Swiss educational / modern AI learning board style. Color palette: white, cool grey, muted sand, graphite, subtle blue accents. Typography: clean sans-serif with structured hierarchy. Make it feel like a premium teaching artifact. Avoid: cluttered layout, vague AI jargon, generic infographic styling, weak hierarchy, confusing visual flow.', 'The "visual prompt anatomy" concept turns abstract prompt-engineering knowledge into a tangible infographic. Specifying each section must include "what it controls" and "why it matters" ensures educational depth. The Swiss educational style direction prevents generic poster output.', 'curated', NULL, NULL, ARRAY['infographic','educational','prompt-engineering','template']::text[]),

-- #8 Prompt Anatomy - Product Packaging
('curated-prompt-anatomy-packaging', 'Prompt Anatomy: Product Packaging', 'Infographics', 'Create a visual prompt anatomy template for a product packaging generation prompt', 'Create a premium, visually structured Visual Prompt Anatomy Template for a premium product packaging generation prompt. The goal is to break down a prompt into clear functional building blocks. Prompt details: Prompt name: Product Packaging Generation Prompt. Use case: image generation. Prompt type: template framework. Intended model behavior: generate commercially realistic, premium packaging visuals with strong brand consistency and clear variant logic. Target user: designers, brand strategists, creative directors. Main objective: teach how to structure a packaging prompt for better visual control. Complexity level: intermediate to advanced. Break into: role assignment, task definition, context block, input variables, output format, style instructions, constraints, examples, quality criteria. Art direction: Swiss educational systems design with premium creative-tech polish. Color palette: white, cool grey, muted sand, graphite, subtle blue accents. Typography: clean sans-serif with structured editorial hierarchy. Material feel: digital learning board, workshop slide, premium prompt framework sheet. Avoid: cluttered layout, generic infographic styling, amateur educational-poster aesthetics.', 'Domain-specific prompt anatomy (packaging) demonstrates that the template concept works across verticals. The structured metadata (use case, complexity level, target user) makes the infographic self-documenting.', 'curated', NULL, NULL, ARRAY['infographic','educational','packaging','template']::text[]),

-- #9 Prompt Anatomy - Landing Page Copy
('curated-prompt-anatomy-copywriting', 'Prompt Anatomy: Landing Page Copywriting', 'Infographics', 'Create a visual prompt anatomy template for a landing page copywriting prompt', 'Create a premium, visually structured Visual Prompt Anatomy Template for a high-converting landing page copywriting prompt. Prompt details: Prompt name: Landing Page Copywriting Prompt. Use case: writing. Prompt type: template framework. Intended model behavior: generate persuasive, audience-aware landing page copy with strong structure, emotional relevance, and conversion clarity. Target user: copywriters, marketers, founders. Main objective: teach how to structure a copywriting prompt for stronger messaging. Complexity level: intermediate. Art direction: editorial strategy board with Swiss educational structure. Color palette: warm white, charcoal, muted beige, pale blue-grey, soft gold accents. Typography: clean sans-serif with refined editorial hierarchy. Optional blocks: headline formula section, audience-awareness variable placeholders, weak vs strong copy prompt comparison, recommended CTA block. Avoid: cluttered layout, generic infographic styling, weak hierarchy.', 'Cross-domain application of the prompt anatomy format to copywriting shows the template''s versatility. The "weak vs strong prompt comparison" optional block adds practical educational value.', 'curated', NULL, NULL, ARRAY['infographic','educational','copywriting','template']::text[]),

-- #10 Prompt Anatomy - Research Brief
('curated-prompt-anatomy-research', 'Prompt Anatomy: Research Brief', 'Infographics', 'Create a visual prompt anatomy template for a structured research brief prompt', 'Create a premium, visually structured Visual Prompt Anatomy Template for a structured research brief prompt. Prompt details: Prompt name: Research Brief Prompt. Use case: research. Prompt type: chained prompt framework. Intended model behavior: produce a clear, source-aware, structured research brief with defined scope, key questions, findings, comparisons, and decision-ready takeaways. Target user: analysts, consultants, strategists, founders. Main objective: teach how to structure a research prompt for better clarity and more decision-useful outputs. Complexity level: advanced. Art direction: consulting-grade systems diagram with editorial tech clarity. Color palette: ivory, graphite, muted slate, pale steel blue, cool grey. Typography: precise sans-serif with structured analytical hierarchy. Optional blocks: source reliability layer, question-framing block, evidence-ranking legend, quality checklist, fallback handling branch. Avoid: cluttered layout, vague AI jargon, generic infographic styling.', 'The "chained prompt framework" type and "source reliability layer" show advanced prompt-engineering concepts. Consulting-grade styling elevates above typical infographic aesthetics.', 'curated', NULL, NULL, ARRAY['infographic','educational','research','template']::text[]),

-- #11 Prompt Anatomy - Cinematic Image
('curated-prompt-anatomy-cinematic', 'Prompt Anatomy: Cinematic Image Generation', 'Infographics', 'Create a visual prompt anatomy template for a cinematic image generation prompt', 'Create a premium, visually structured Visual Prompt Anatomy Template for a cinematic image generation prompt. Prompt details: Prompt name: Cinematic Image Generation Prompt. Use case: image generation. Prompt type: template framework. Intended model behavior: generate visually rich, compositionally controlled, cinematic images with clear subject definition, atmosphere, styling, and output consistency. Target user: designers, art directors, AI creators, visual storytellers, prompt engineers. Main objective: teach how to structure an image prompt for better visual control, style consistency, and more intentional outputs. Complexity level: intermediate to advanced. Art direction: creative-tech learning board with Swiss diagram logic and cinematic polish. Color palette: white, graphite, muted sand, soft indigo, pale silver accents. Optional blocks: subject block, camera/framing block, lighting block, style block, constraints block, output preview area, weak vs strong prompt comparison. Avoid: cluttered layout, generic infographic styling, confusing visual flow.', 'Self-referential prompt anatomy for image generation prompts. The optional blocks (subject, camera, lighting, style, constraints) mirror the actual structure taught in the anatomy, creating a meta-educational loop.', 'curated', NULL, NULL, ARRAY['infographic','educational','cinematic','template']::text[]),

-- #12 Isometric Vehicle Diorama
('curated-isometric-vehicle-diorama', 'Isometric Vehicle Diorama', 'Cinematic', 'Create an isometric diorama of a famous vehicle on a themed base', 'Present a clear, 45° top-down isometric miniature 3D diorama of the iconic vehicle DeLorean DMC-12 (Back to the Future). The vehicle is the main focus, placed on a small raised diorama-style base that reflects its most recognizable environment (road with fire trails), with subtle contextual details and tiny stylized figures. Use soft refined textures, realistic PBR materials, and gentle cinematic lighting. The vehicle should feel premium, collectible, and instantly recognizable at a glance. Use a clean solid dark gray background with no gradients. At the top-center, display "DELOREAN DMC-12" in large bold text. Directly beneath it, display a short descriptor in medium text. Composition: perfectly centered, square 1080x1080, ultra-clean high-clarity diorama aesthetic.', 'The 45° isometric angle + raised base creates a "collectible figure in a display case" feel. PBR materials instruction ensures realistic surface rendering. Template structure: swap [VEHICLE NAME] and [BACKGROUND COLOR] for any vehicle.', 'curated', NULL, NULL, ARRAY['isometric','diorama','vehicle','3d']::text[]),

-- #13 Technical Blueprint Drawing
('curated-technical-blueprint', 'Technical Blueprint Drawing', 'Infographics', 'Create a technical blueprint drawing of a product with orthographic views', 'Mechanical wristwatch, technical blueprint drawing, orthographic view, front view + side view + top view, white vector line art, thin construction lines, precise measurements, annotation labels, dimension arrows, grid background, deep blue background, minimal design, engineering schematic style, high detail.', 'Comma-separated keyword stacking is efficient for technical illustrations. The blue background + white line art is a classic blueprint aesthetic that GPT Image 2 renders accurately. Orthographic multi-view layout is a specific engineering convention the model understands.', 'curated', NULL, NULL, ARRAY['blueprint','technical','engineering','orthographic']::text[]),

-- #14 Constructivist Graphic Design Poster
('curated-constructivist-poster', 'Constructivist Graphic Design Poster', 'Posters', 'Create a constructivist graphic design poster of an anime character', 'Constructivist graphic design poster, pure color block style, vector graphic style, no substitutions, no shadows, no lighting effects. The theme is Violet Evergarden, with colors matching the character design. The character''s body proportions should align with the art style. Clothing is represented using large areas of solid color. Half-body or mostly half-body composition, with the character centered. Geometric shapes (squares, circles, diagonal lines) surround the character to construct the visual layout. The shapes participate in the composition but must not cover the face. All color details must be solid color blocks. Edges should be sharp, clean, and textureless. Overall style: modern graphic design poster, not illustration. 9:16 vertical format.', 'Strong negative constraints ("no shadows, no lighting effects, not illustration") force a specific flat graphic style. The "shapes participate in composition but must not cover the face" rule prevents common AI failures with geometric overlays.', 'curated', NULL, NULL, ARRAY['poster','constructivist','anime','vector']::text[]),

-- #15 Scientific Creature Infographic
('curated-scientific-creature-infographic', 'Scientific Creature Infographic', 'Infographics', 'Create a scientific educational infographic about a creature with anatomy diagrams', 'A detailed scientific educational infographic about a Red Dragon. The layout features a large, hyper-realistic digital painting of the creature in the center with a fierce expression. Surrounding the main image are various modular sections: a 3D skeletal structure, a skull anatomy diagram with labels, a size comparison silhouette against a human, a world map showing its habitat, and a vertical "Hunting Strategy" series of small action illustrations. The background is a clean, off-white parchment texture. Use bold, clean sans-serif typography for headings like "ANATOMY," "DIET," and "EXTINCTION." The style should be professional and informative, resembling a page from a high-end natural history encyclopedia.', 'Modular section approach (skeleton, skull, size comparison, habitat map, hunting strategy) gives structure without being rigid. The "natural history encyclopedia" style anchor is more specific than generic "infographic" and produces a consistent aesthetic.', 'curated', NULL, NULL, ARRAY['infographic','scientific','creature','encyclopedia']::text[]),

-- #16 Crayon Style Social Media Profile
('curated-crayon-social-profile', 'Crayon Style Social Media Scene', 'Open-Ended Creative', 'Create a crayon-style illustration of a social media profile drawn like a child', 'Crayon style illustration of a social media profile scene, drawn like a 10-year-old child, simple shapes, imperfect lines, hand-drawn, naive art style, bright playful crayon colors, white paper background, soft cute innocent aesthetic, whimsical doodles, stars, clouds, candy, castles, towers, hearts, colorful decorations, childlike imagination, messy coloring, textured crayon strokes, sketchy outlines, pastel + vibrant mix, dreamy playful composition.', 'The "drawn like a 10-year-old child" instruction combined with specific art vocabulary (naive art style, imperfect lines, messy coloring) creates an authentic childlike quality without looking AI-generated. Keyword stacking of decorative elements gives the model creative freedom within constraints.', 'curated', NULL, NULL, ARRAY['illustration','crayon','childlike','social-media']::text[]),

-- #17 Minimalist Country Sticker Collection
('curated-minimalist-sticker-collection', 'Minimalist Country Sticker Collection', 'Infographics', 'Generate a minimalist sticker collection inspired by a country', 'Generate a minimalist sticker collection inspired by Japan, showcasing simplified versions of key landmarks, famous dishes, and cultural icons, flat design, limited color palette, clean geometry, subtle shadows, modern aesthetic, evenly spaced sticker layout, high detail, with "JAPAN" placed at the top center in a matching minimalist style.', 'The combination of "minimalist" + "flat design" + "limited color palette" + "clean geometry" produces cohesive sticker sheets. Specifying both landmarks AND dishes AND cultural icons ensures variety within the collection.', 'curated', NULL, NULL, ARRAY['sticker','minimalist','travel','flat-design']::text[]),

-- #18 Technical Annotation Photo Infographic
('curated-technical-annotation-photo', 'Technical Annotation Photo Infographic', 'Infographics', 'Create an infographic combining a realistic photo with technical pen annotations', 'Create an infographic image of the human heart, combining a realistic photograph or photoreal render of the object with technical annotation overlays placed directly on top. Use black ink-style line drawings and text (technical pen / architectural sketch look) on a pure white studio background, including: key component labels, internal cutaway or exploded-view outlines, measurements, dimensions, and scale markers, material callouts and quantities, arrows indicating function, force, or flow, simple schematic or sectional diagrams where relevant. Place the title "HUMAN HEART" inside a hand-drawn technical annotation box in one corner. Style: the real object remains clearly visible beneath the annotations. Annotations feel sketched, technical, and architectural. Clean composition with balanced negative space. Educational, museum-exhibit / engineering-manual vibe. Visual style: minimal technical illustration aesthetic, black linework over realistic imagery, precise but slightly hand-drawn feel. Color palette: white background, black annotation lines and text only. No colors. Output: 1080x1080, ultra-crisp.', 'The hybrid of "realistic photo underneath + hand-drawn technical annotations on top" is a specific and unusual visual style that produces striking results. The "museum-exhibit / engineering-manual vibe" anchors the aesthetic precisely.', 'curated', NULL, NULL, ARRAY['infographic','technical','annotation','hybrid']::text[]),

-- #19 Isometric Technical Infographic
('curated-isometric-tech-infographic', 'Isometric Technical Device Infographic', 'Infographics', 'Create a technical infographic of a device with isometric 3D perspective and annotations', 'Create a technical infographic of iPhone 16 Pro with a 45-degree isometric 3D perspective showing the device slightly tilted to reveal depth and dimension. Combine a realistic photoreal render with black ink technical annotations on pure white background. Include: Key component labels with color-coded callout boxes, internal component visibility through transparent/cutaway sections, measurements, dimensions, and precise scale markers, material callouts and quantities. Color-coded arrows for function/flow: RED (power/battery), BLUE (data/connectivity), ORANGE (thermal/processor), GREEN (sensors/haptics). Simple schematics or cross-sectional diagrams where relevant. Place "iPHONE 16 PRO" title in a hand-drawn technical box (top-left corner). Style: Black linework (technical pen/architectural), sketched but precise. Object remains clearly visible. Educational museum-exhibit vibe. Perspective: Isometric 3D angle — tilted to show depth, dimension, and internal architecture. Like a professional product teardown or engineering manual. Colors: ~10-15% accent density. Black dominant. White background. Output: 1080x1080, ultra-crisp.', 'Adding isometric 3D perspective to technical annotations creates a product-teardown aesthetic. The color-coded arrow system (RED=power, BLUE=data, ORANGE=thermal, GREEN=sensors) adds information hierarchy without cluttering.', 'curated', NULL, NULL, ARRAY['infographic','isometric','teardown','technical']::text[]),

-- #20 Agency Brand Identity System Poster
('curated-brand-identity-system', 'Agency-Grade Brand Identity System', 'Posters', 'Upload a logo and create a complete brand identity system poster', 'Agency-Grade Brand Identity System Poster. Upload a logo. From it, construct a complete, investment-worthy brand identity system poster. Format: Vertical 4:5, multi-column grid, layered, dense, intentional — zero wasted space. Sections: 01 Brand Header (brand name in commanding typography, brand statement 6 words max, three soul descriptors). 02 Color System (primary 3-5 colors, secondary 3-5 colors, accent colors, each with wide swatch block, HEX code, role label). 03 Typography System (headline, subheadline, body tiers with examples). 04 Visual Language (image style, lighting quality, texture references, 3-5 art-directed mood tiles). 05 Brand Applications (product packaging render, website hero, mobile app screen, social media posts, business card front/back, out-of-home ad). 06 Design System (buttons, cards, input fields, navigation, spacing scale). 07 Iconography (6-10 icons in same visual grammar as logo). 08 Patterns & Motifs (derived from logo geometry). 09 Material & Depth (shadows, surface textures, reflections, layer depth). Scale target: 30-50 distinct visual elements. Quality: must look like it costs $15,000 to produce.', 'The nine-section structure with specific element counts (30-50 elements, 6-10 icons, 3-5 mood tiles) gives the model concrete targets. "Must look like it costs $15,000 to produce" is an effective quality anchor. The "Every element extracted from logo DNA" rule ensures visual cohesion.', 'curated', NULL, NULL, ARRAY['brand','identity','system','poster']::text[]),

-- #21 Cocktail Exploded View Grid
('curated-cocktail-exploded-view', 'Cocktail Exploded View Recipe Grid', 'Infographics', 'Create a 2x2 grid of cocktail ingredient exploded views with recipe blueprints', '2x2 grid of 4 famous hidden gem cocktails: Penicillin, Last Word, Paper Plane, Jungle Bird. Each cell: isometric exploded view of cocktail ingredients and tools with blueprint-style recipe measurements UI. Dark slate studio background with warm bar lighting gradient. Each cocktail shows ingredients floating in precise layers above the glass, measurement annotations, tool callouts, and garnish details. Style: premium cocktail bar menu meets engineering diagram. Avoid: paper umbrellas, messy spilled liquid, straight-on product shot of just a glass.', 'The exploded-view approach to cocktail recipes is novel — ingredients floating in layers above the glass creates visual interest while being informative. The "Avoid" list prevents cliché bar photography. Dark background + warm lighting mimics speakeasy ambiance.', 'curated', NULL, NULL, ARRAY['infographic','cocktail','recipe','exploded-view']::text[]),

-- #22 Coffee Brewing Cycle Infographic
('curated-coffee-brewing-cycle', 'Coffee Brewing Cycle Infographic', 'Infographics', 'Create a circular infographic showing coffee brewing methods matched to a bean type', 'A circular wheel infographic divided into 4 quadrants showing the brewing cycle for Ethiopian Yirgacheffe coffee. Methods: Espresso, V60, French Press, Cold Brew. Each quadrant shows the specific brewing vessel, coffee grounds at correct grind size, and the resulting cup. Style: warm cozy lighting, steam effects, hyper-realistic liquid simulation. Title: "BREWING ETHIOPIAN YIRGACHEFFE". Include a tasting notes wheel near each method (Floral, Citrus, Berry, Nutty). Rendered coffee grounds with accurate texture differences (fine for espresso, coarse for French Press). Specific glass/metal/ceramic vessels filled with coffee at different extraction stages.', 'The circular quadrant layout creates a natural information hierarchy. Specifying accurate grind-size textures and vessel materials adds educational accuracy. The tasting notes wheel connects each method to flavor outcomes.', 'curated', NULL, NULL, ARRAY['infographic','coffee','brewing','circular']::text[]),

-- #23 DTC Brand Style Guide (Image Edit - needs logo)
('curated-dtc-brand-style-guide', 'DTC Brand Style Guide', 'Image Edits', 'Analyze an uploaded logo and create a clean, modern brand style guide', 'You are a world-class DTC brand designer. Analyse the uploaded logo/packaging and create a clean, modern, high-end brand style guide. Focus on clarity, consistency, and real-world usability across ecommerce, ads, and social. Structure: 1. Brand Essence (3-5 words + one brand statement). 2. Color System (primary colors with HEX, secondary/supporting colors, background recommendations). 3. Typography (font pairings headline + body, style direction, usage rules). 4. Visual Style Direction (overall design style, use of shadows/lighting/gradients, texture/material suggestions). 5. Layout Principles (spacing rules, grid style, image/text balance). 6. Imagery & Creative Direction (product photography style, lifestyle direction, do''s and don''ts). 7. UI / Ad / Social Direction (website, ads, social translations). 8. Quick Win Ideas (3-5 immediate visual improvements). Keep everything: Minimal, Modern, Premium DTC, Conversion-focused. Avoid generic advice. Make it feel like a real brand system used by top ecommerce brands.', 'The structured 8-section format covers all touchpoints a DTC brand needs. The "conversion-focused (not just pretty)" constraint prevents decorative-only outputs. Platform-specific translations (website vs ads vs social) add practical value.', 'curated', NULL, NULL, ARRAY['brand','style-guide','dtc','ecommerce']::text[]),

-- #24 Retro Sci-Fi Racing Poster
('curated-retro-scifi-racing', 'Retro Sci-Fi Racing Poster', 'Posters', 'Create a retro sci-fi racing poster with hover vehicles on a cosmic track', 'A hyper-dynamic retro sci-fi racing poster, multiple futuristic hover vehicles tearing through a glowing cosmic track that spirals like a ribbon through open space. The track emits light trails that bend and twist, creating exaggerated perspective distortion — the closest vehicle appears massive and warped, almost breaking the frame. Vehicles have bold, stylized shapes with exaggerated fins, glowing engines, and transparent cockpit domes. Inside the lead vehicle: a pilot barely visible, helmet reflecting neon streaks. Background: massive planets with rings slicing diagonally through the composition, distant space stations, streaking stars stretched by motion. Composition: extreme wide-angle lens effect, diagonal energy flow, everything converging toward a vanishing point. Lighting: intense neon highlights (magenta, cyan, orange) against deep black space, strong contrast. Style: 1960s-1980s retro futurism travel poster meets arcade sci-fi cover art, airbrushed gradients, bold graphic shapes. Texture: visible film grain, analog noise, slight motion blur artifacts, print fading, worn edges, subtle fold creases. Palette: saturated but slightly aged — hot pink, electric blue, amber, deep navy. Extra detail: tiny sparks, micro debris, glowing particles trailing behind vehicles. Mood: speed, danger, exhilaration, controlled chaos.', 'Era-specific style anchor ("1960s-1980s retro futurism travel poster meets arcade sci-fi cover art") gives a precise aesthetic target. Physical print artifacts (film grain, fold creases, print fading) add authenticity. The exaggerated perspective + diagonal composition creates dynamic energy.', 'curated', NULL, NULL, ARRAY['poster','retro','sci-fi','racing']::text[]),

-- #25 Borderless Grid Panels
('curated-borderless-grid-panels', 'Borderless Grid Memory Panels', 'Storyboards', 'Create a borderless grid where each panel is an independent image of a subject', 'Create a 4x3 borderless grid where each panel is an independent image of a young woman. Maintain strong subject consistency across all panels, with consistent color and lighting. Depict summer vacation memories with a warm, nostalgic, wistful mood in nostalgic cinematic realism style. No text. No gap. Each panel: different angle, different moment, same person, same color grade. Panels flow as a visual narrative without explicit story — morning coffee, walking through old streets, reading by a window, swimming in the sea, golden hour on a balcony, market flowers, train platform, sunset silhouette, laughing with locals, handwritten postcard, night lanterns, sleeping on a train.', 'The "borderless + no gap" instruction creates a seamless photo-mosaic effect. Subject consistency + varied angles mimics a real photo diary. Listing specific scene beats per panel gives narrative coherence while maintaining visual variety.', 'curated', NULL, NULL, ARRAY['storyboard','grid','consistency','cinematic']::text[]),

-- #26 Scrapbook Photo Enhancement (Image Edit - needs photo)
('curated-scrapbook-photo-enhancement', 'Cozy Scrapbook Photo Enhancement', 'Image Edits', 'Transform a photo into a scrapbook composition with mini character versions', 'Transform the provided reference image into a cozy aesthetic scrapbook-style composition while strictly preserving the original subject, identity, pose, lighting, and background. Add multiple small "mini version" characters of the same person (chibi / doll-like style), placed naturally around the scene (on objects, table, shoulder). These mini figures must match the subject''s face, hairstyle, outfit, and vibe consistently, styled as cute 3D collectible figurines. Show them doing different activities (reading, posing, taking photos, relaxing). Overlay handwritten-style doodles and annotations across the image: arrows, hearts, stars, sparkles, icons, and playful captions connected to elements in the scene. Use a soft pastel color palette (white base with pink, peach, blue accents). Keep the frame visually rich and filled but balanced and clean. Style: warm, cozy lighting, dreamy Instagram scrapbook aesthetic, soft depth of field, highly detailed, polished but playful. The final result must look like the SAME original image enhanced with mini alter-egos and aesthetic annotations — not a recreated or different scene.', 'The "strictly preserving" + "not a recreated or different scene" constraints prevent the common AI failure of regenerating the photo from scratch. Mini figure requirements (match face, hairstyle, outfit) enforce consistency. The "3D collectible figurines" style anchor is more specific than generic "chibi."', 'curated', NULL, NULL, ARRAY['image-edit','scrapbook','chibi','aesthetic']::text[]),

-- #27 Multi-Page Brand Kit
('curated-nightshade-brand-kit', 'Multi-Page Brand Kit (NIGHTSHADEAI)', 'Posters', 'Create a polished multi-page brand kit for a playful, futuristic tech brand', 'Create a polished multi-page brand kit for a company called NIGHTSHADEAI. The brand should feel playful, futuristic, vibrant, and design-forward, blending the energy of a toy-inspired product with the sophistication of a premium creative tech brand. Use a bold, experimental visual identity with bright color, clean geometry, modern typography, dynamic motion cues, and slightly surreal imagery. The overall mood should feel inventive, youthful, rhythmic, tactile, and high-concept, with a balance of fun consumer product culture, fashion-like presentation, and contemporary digital design. Include a sense of product obsession, visual experimentation, packaging exploration, editorial photography, immersive retail, and cross-platform brand application. Make it feel like a confident, contemporary brand world that is both accessible and art-directed, with strong graphic cohesion and a premium creative-studio aesthetic. Colours to be used: butter yellow, milk white and midnight black.', 'The brand personality brief is exceptionally detailed (playful yet sophisticated, toy-inspired yet premium) which gives the model clear creative constraints. Specific color names ("butter yellow, milk white, midnight black") are more evocative than hex codes. The "multi-page" instruction produces a brand world rather than a single poster.', 'curated', NULL, NULL, ARRAY['brand','identity','tech','playful']::text[]),

-- #28 Doraemon RPG Battle Screenshot
('curated-doraemon-rpg-battle', 'Doraemon RPG Battle Screenshot', 'UI Mockups', 'A photorealistic 3D RPG mobile game screenshot with Doraemon characters', 'A high-resolution, photorealistic 3D action RPG mobile game screenshot of an epic battle featuring Doraemon characters. Perspective from behind Nobita. Background: post-apocalyptic urban scene with rubble, fires, purple lightning. Characters: Doraemon holding a gatling-style cannon with blue energy, Nobita in combat stance with slingshot weapon, Giant Gian as boss with spiked mace and glowing red eyes. Nameplates: Doraemon (Lv.30, HP:2150/2420), Nobita (Lv.30, HP:1980/2200), Gian (Lv.??, HP:85670/100000). UI Elements: Left panel "MISSIONS" with quest text, Right panel "BOSS MISSION", Bottom right skill buttons (Heavy Strike, Basic Attack, Bamboo Copter Flight, Item Bag, Tumble Dodge), Bottom center item bar with stamina 120/130, Mini-map top right with skull icon. Cinematic lighting with cool blue weapon light, warm orange firelight, cold purple lightning.', 'The extreme specificity of UI elements (exact HP values, skill names, item counts, stamina numbers) is what makes game UI screenshots convincing. Mixing cute IP characters with dark RPG aesthetics creates an interesting contrast. The behind-the-shoulder perspective matches real action RPG camera angles.', 'curated', NULL, NULL, ARRAY['game','rpg','ui','doraemon']::text[]),

-- #29 TV Show Character Relationship Diagram
('curated-tv-character-diagram', 'TV Show Character Relationship Diagram', 'Infographics', 'Create a character relationship diagram for a TV series', 'Create a character relationship diagram for the TV series Breaking Bad. Emphasize character portraits, avoid excessive white space, ensure the image is full and textured, use high-resolution portraits, and maintain a 3:2 aspect ratio. Show relationship lines with labels (family, partnership, rivalry, manipulation, mentor). Central focus on Walter White with connections radiating outward. Include: Jesse, Skyler, Hank, Gus Fring, Mike, Saul, Todd. Use color coding for relationship types. Background: dark with subtle chemistry motifs.', 'The "avoid excessive white space, ensure the image is full and textured" instruction prevents the sparse, disconnected look common in AI-generated diagrams. Specifying relationship types (family, partnership, rivalry) as labeled connections adds information density.', 'curated', NULL, NULL, ARRAY['infographic','relationship','tv-show','diagram']::text[]),

-- #30 Manga Comic Strip
('curated-manga-study-scene', '6-Panel Manga Comic Strip', 'Storyboards', 'Create a 6-panel manga page about late-night studying', '6-panel manga page, 2:3 vertical portrait, detailed anime manga style with high contrast and cinematic lighting. Thick white panel divider lines clearly separating each panel, visible white gutters, hard black border around each panel, traditional manga page grid layout. Color palette: deep navy blue dark room background, warm amber desk lamp glow, cool blue laptop screen light, bright red panic effects, white speech bubbles, clean bright white divider lines. Characters: girl A with twin braids and glasses, dark school uniform, red bow; girl B with short brown hair, dark school uniform, asleep on desk initially. Setting: dark bedroom study desk at 2:47am, single warm desk lamp, open laptop, scattered notes. Panel 1 (top, wide): Dark room, warm lamp + cool laptop glow, Character A studying, B asleep, clock shows 2:47 AM. Panel 2 (upper middle left): Close-up A''s face lit by blue laptop, eyes wide in horror, "Wait... did I save it?!" Panel 3 (upper middle right): A hollow bloodshot eyes, "I don''t remember what sleep is..." Panel 4 (lower middle, wide): A SLAMS desk screaming "IT''S ALL GONE!!", books fly, B jolts awake. Panel 5 (upper bottom): A holds laptop with AUTOSAVE notification, manic grin. Panel 6 (lower bottom): B deadpan foreground, A kissing laptop in background.', 'Extremely detailed panel-by-panel specification with exact layout positions, lighting per panel, and speech bubble text produces manga that reads coherently. The "thick white panel divider lines" instruction solves the common problem of panels bleeding together. Dual-lighting (warm lamp + cool screen) creates authentic nighttime study atmosphere.', 'curated', NULL, NULL, ARRAY['manga','comic','anime','multi-panel']::text[]),

-- #31 Apple Vision Pro Marketing Poster
('curated-apple-vision-pro-poster', 'Apple Vision Pro Marketing Poster', 'Posters', 'Create a premium tech product marketing poster for Apple Vision Pro', 'High-end vertical (9:16) tech product marketing poster for Apple Vision Pro. Deep dark space-like background with subtle cool blue and silver gradients. Clean bold modern sans-serif font throughout. Section 1 Hero: Apple logo + "Vision Pro" in silver, main title "INFINITE SPACE, BOUNDLESS VISION", tagline below, four circular feature icons (micro-OLED, 180° SPATIAL VIEW, OPTIC ID, EYE TRACKING). Large dramatic render of headset at dramatic angle with glowing EyeSight display. Section 2 Key Specs: Title "POWERFUL PERFORMANCE", five dark rounded feature blocks horizontal (23 Million Pixels, 180° View, 3D Spatial Audio, Optic ID, Lightweight ~600g). Section 3 Center: Large block with someone wearing Vision Pro surrounded by floating virtual screens. Section 4 Display: Split comparison — standard flat display vs Vision Pro micro-OLED (sharper, more vibrant, three-dimensional). Section 5 Control: Eye tracking + hand gesture comparison. Price "$3,499" subtle bottom-right. Overall: ultra-premium dark aesthetic, silver and blue-tinted glass accents, mysterious and otherworldly.', 'Five-section structured layout mirrors real DJI/Apple marketing posters. The comparison shots (standard vs Vision Pro) are a proven marketing technique. Subtle price placement and cinema-grade dark aesthetic sell premium positioning. Specific feature counts and values (23M pixels, 180°, $3,499) add authenticity.', 'curated', NULL, NULL, ARRAY['poster','tech','product','apple']::text[]),

-- #32 Fluid Foam Logo (Brand Logo Art)
('curated-fluid-foam-logo', 'Fluid Foam Logo Art', 'Posters', 'Create a brand logo formed from living fluorescent foam and bubbles', 'Macro Fluid Photography: the Nike swoosh logo formed entirely from living fluorescent foam and bubble liquid — as if poured into a logo-shaped mold on a black surface at maximum bubble activity. ABSOLUTE RULE: The fluid mass has the exact shape of the Nike logo. Not a circle, not a blob. The outer silhouette IS the logo outline. PHASE 1 FLUID: thick viscous fluid, fluorescent orange at maximum saturation, self-luminous UV-reactive quality. Thin membranes lighter, deep pools darker. PHASE 2 BUBBLES: Full hierarchy — large 10-18mm (4-8), medium 4-9mm (15-25), small 1.5-3mm (30-50), micro 0.5-1mm (50-100+). Each bubble: sphere of trapped air, 0.1-0.3mm membrane, soap film iridescence, white crescent highlight upper-left. PHASE 3 DUAL-STATE: Left zone dense chaotic foam, right zone smooth liquid pool, transition through center. PHASE 4 LIGHTING: Large softbox upper-LEFT 20-30° from vertical, 5500K neutral white. Bubble dome highlights in upper-left. PHASE 5: Background absolute black #000000. 1:1 square. Logo occupies 60-70% of frame centered. Zero fluid outside logo boundary.', 'The six-phase structure with absolute rules creates a physically accurate fluid simulation. The "silhouette IS the logo" rule with explicit failure checks prevents the model from defaulting to a circle or blob. Dual-state (foam vs liquid) adds visual interest and demonstrates the material''s properties.', 'curated', NULL, NULL, ARRAY['poster','logo','fluid','macro']::text[]),

-- #33 Logo Concept Generator
('curated-logo-concept-generator', 'Logo Concept Generator Framework', 'Infographics', 'A prompt framework for generating 5 different logo concepts with strategic reasoning', 'You are a world class logo designer and creative director with 20 years of experience. My brand name: [YOUR BRAND NAME]. My industry: [YOUR INDUSTRY]. My brand personality: [DESCRIBE IT]. My target audience: [DESCRIBE THEM]. Brands whose visual identity I admire: [LIST 3]. Brands whose visual identity I hate: [LIST 3]. My preferred style: [e.g. minimal, bold, geometric, organic, retro, futuristic]. Generate 5 completely different logo concepts. For each concept give me: the core visual idea and what it represents symbolically, the shape language and why it works, the typography direction (serif, sans serif, script, custom), what emotion it triggers at first glance, why this concept works for my specific audience, how it would look on a business card, an app icon and a billboard, what makes this concept timeless rather than trendy. Then tell me which concept you would choose if this was your brand and exactly why.', 'This is a text-prompt framework (not image generation) that produces strategic logo direction. The "brands I admire vs hate" input gives the model clear aesthetic boundaries. The cross-platform test (business card + app icon + billboard) ensures scalability thinking.', 'curated', NULL, NULL, ARRAY['brand','logo','framework','strategy']::text[]),

-- #34 Brand Identity Foundation
('curated-brand-identity-foundation', 'Brand Identity Foundation Framework', 'Infographics', 'A prompt framework for building complete brand identity strategy', 'You are a world class brand strategist and visual identity designer. My business name: [YOUR BUSINESS NAME]. What my business does: [ONE SENTENCE]. My target audience: [DESCRIBE IN DETAIL]. My competitors: [LIST 3-5]. The feeling I want my brand to trigger: [e.g. trust, excitement, luxury]. Words I want associated with my brand: [LIST 5-10]. Words I never want associated: [LIST 5-10]. Build me a complete brand identity foundation: my brand archetype and why it fits, my brand personality in 5 specific human traits, my brand voice guide with examples of how I should and should not sound, my core brand promise in one sentence, the 3 emotions my brand should trigger in order, what makes my brand fundamentally different from competitors, the one word that should define my entire brand.', 'Strategic brand framework that produces actionable identity decisions. The "words I never want associated" input is as important as positive associations — it prevents generic outputs. The "3 emotions in order" exercise creates a customer journey narrative.', 'curated', NULL, NULL, ARRAY['brand','strategy','identity','framework']::text[]),

-- #35 Color Palette Framework
('curated-color-palette-framework', 'Brand Color Palette Framework', 'Infographics', 'A prompt framework for building a psychology-driven brand color palette', 'You are a color psychology expert and brand designer. My brand name: [YOUR BRAND NAME]. My industry: [YOUR INDUSTRY]. My target audience: [DESCRIBE IN DETAIL]. The emotion I want to trigger first: [e.g. trust, energy, luxury]. My top 3 competitors and their brand colors: [LIST THEM]. Colors I love: [LIST]. Colors I hate: [LIST]. Build me a complete brand color palette: a primary color with exact HEX code and psychological explanation, two secondary colors with HEX codes that complement the primary, one accent color for calls to action, one neutral color for backgrounds and text, how each color makes my target audience feel and why, how my palette differs from competitors, real world examples across website, social media, and packaging, what color combinations to never use together and why.', 'Color psychology framing produces more intentional palette choices than aesthetic-only approaches. Competitor color analysis ensures differentiation. The "never use together" constraint prevents palette misuse in implementation.', 'curated', NULL, NULL, ARRAY['brand','color','psychology','framework']::text[]),

-- #36 Typography Direction Framework
('curated-typography-framework', 'Typography Direction Framework', 'Infographics', 'A prompt framework for building a complete brand typography system', 'You are a typography expert and brand designer. My brand name: [YOUR BRAND NAME]. My brand personality: [5 WORDS]. My industry: [YOUR INDUSTRY]. My target audience: [DESCRIBE]. The feeling my typography should trigger: [e.g. authority, friendliness, innovation]. Brands whose typography I love: [LIST 3]. Build me a complete typography system: a primary display font with exact font name, where to find it, and why it captures my brand personality; a secondary body font that pairs with it; an accent font for special moments; exact size hierarchy for headlines, subheadings, body, captions; letter spacing and line height recommendations; how to use these fonts together without clashing; free alternatives for each; the one typography mistake most brands in my industry make.', 'Naming specific existing fonts (with sources) produces actionable results vs generic style descriptions. The "one mistake most brands make" output provides defensive design knowledge. Free alternatives ensure accessibility regardless of budget.', 'curated', NULL, NULL, ARRAY['brand','typography','system','framework']::text[]),

-- #37 Complete Brand Identity Package
('curated-complete-brand-package', 'Complete Brand Identity Package', 'Infographics', 'A prompt framework for generating a full brand identity system in one response', 'You are a world class brand agency creative director. My business name: [YOUR BUSINESS NAME]. What I do: [ONE SENTENCE]. My target audience: [DESCRIBE]. My brand personality: [5 WORDS]. My industry: [YOUR INDUSTRY]. My top competitors: [LIST 3]. My budget for design tools: [FREE OR PAID]. Deliver my complete brand identity system: brand strategy (archetype, personality, promise, positioning), logo concept with 3 variations (primary, secondary, icon), complete color palette with HEX codes and usage rules, typography system with font names and hierarchy, visual direction guide (photography, illustration, layout), brand voice guide with tagline options, social media visual templates described in enough detail to generate with AI immediately, the 3 most important brand rules I should never break. Deliver as a structured brand bible understandable in under 10 minutes.', 'The "understandable in under 10 minutes" constraint forces conciseness. Including budget awareness (free vs paid) makes outputs practical. The "social media templates described in enough detail to generate with AI" creates a bridge to image generation tools.', 'curated', NULL, NULL, ARRAY['brand','identity','complete','framework']::text[]),

-- #38 Forbes-Style Magazine Cover (Image Edit)
('curated-forbes-magazine-cover', 'Forbes-Style Magazine Cover', 'Image Edits', 'Create a premium magazine cover from an uploaded photo', 'Create a premium vertical magazine cover from the uploaded photo. Keep the subject''s exact identity and facial features. Head-and-shoulders portrait, facing forward, confident gaze, slight smile, one hand subtly raised. Dress the subject in a tailored black suit. Background: blurred high-rise office with glass windows, city skyline at dusk, subtle blue and gold data visuals. Add a bold red magazine title at the top: "ASCEND." Add a "40 UNDER 40" badge with a star on the upper left. Main headline in large white text: "THE INNOVATION ARCHITECT." Subheadline: "[NAME] on rewriting the rules of business and shaping the AI economy." Side cover lines: "THE COMPLETE LIST," "EXCLUSIVE INTERVIEW," "MEET THE DISRUPTORS." Bottom text: "MAY 2026" and "ASCENDMAG.COM." Style: modern, photorealistic, polished, luxury business editorial.', 'The magazine cover template preserves identity while adding aspirational context. Specific typographic hierarchy (title, badge, headline, subheadline, side cover lines, bottom text) mirrors real magazine layout conventions. The "luxury business editorial" style anchor produces the right aesthetic register.', 'curated', NULL, NULL, ARRAY['image-edit','magazine','portrait','editorial']::text[]),

-- #39 Full Brand Kit Poster
('curated-full-brand-kit', 'Full Brand Kit Board', 'Posters', 'Create a premium brand kit board showing complete brand identity', 'Create a premium brand kit board for a coffee brand called "ROAST REPUBLIC", presented like a professional branding studio slide. Show the existing brand identity in a clean, organized visual presentation. Include primary logo, secondary logo, icon, earth-tone color palette (espresso brown, cream, sage green, charcoal), typography pairing, branded packaging (coffee bag + cup), social media mockup, and simple brand pattern elements. Style: modern minimal editorial. Use a clean editorial grid, realistic materials, strong hierarchy, and polished presentation. Text to include: "ROAST REPUBLIC — Brand Identity System"', 'The "professional branding studio slide" framing produces clean grid layouts rather than cluttered collages. Including both logo variations AND applications (packaging, social) shows the system working. Specific materials (realistic renders) elevate above flat mockups.', 'curated', NULL, NULL, ARRAY['brand','kit','identity','presentation']::text[]),

-- #40 Epic Sci-Fi Movie Poster
('curated-epic-scifi-movie-poster', 'Epic Sci-Fi Movie Poster (ECHOES)', 'Posters', 'Create an epic cinematic sci-fi movie poster', 'Epic cinematic sci-fi movie poster for a fictional film titled ECHOES. Dark blue and orange color grade, massive space opera composition. Giant close-up of a young woman in a futuristic astronaut helmet dominating the top half, intense reflective face. Large planets and moons in the background, starfields, warships and small spacecraft flying across the scene. Two serious male characters and one female character layered in the middle foreground, a tall armed humanoid robot on the right. Futuristic alien city skyline, glowing pyramid structure in the center, lone figure standing in the foreground facing the city. Sunset on the horizon, atmospheric fog, scale and depth. Glossy cinematic lighting, highly detailed armor and ships. IMAX-style blockbuster poster, photoreal, sharp focus, symmetrical heroic layout. Title text "ECHOES" at the bottom, tagline at the top, coming soon credits and cinema logos.', 'The layered composition (close-up face top → mid characters → city → lone figure foreground) mirrors real blockbuster poster design. Blue/orange complementary color grade is cinema-standard. Including credits bar and cinema logos adds authenticity. The pyramidal subject hierarchy guides the eye.', 'curated', NULL, NULL, ARRAY['poster','movie','sci-fi','cinematic']::text[]),

-- #41 Football Match Poster
('curated-bundesliga-match-poster', 'Bundesliga Match Poster', 'Posters', 'Create a dramatic football match poster', 'Dramatic Bundesliga match poster, Borussia Dortmund vs SC Freiburg, split yellow and red background, large player portraits facing each other at the top, two full-body players below, gritty texture, bold sports typography, club badges, stadium at the bottom, cinematic lighting, high contrast, ultra-detailed, professional football promo poster.', 'The split background (yellow/red matching team colors) creates instant visual tension. Face-to-face portraits at top establish rivalry. Adding stadium at bottom grounds the image in a specific venue. Gritty texture adds sports-broadcast energy.', 'curated', NULL, NULL, ARRAY['poster','sports','football','match']::text[]),

-- #42 MLB All-Star Game Poster
('curated-mlb-allstar-poster', 'MLB All-Star Game Vintage Poster', 'Posters', 'Create a vintage-style MLB All-Star Game poster', 'Vintage-style MLB All-Star Game 2026 poster, Philadelphia theme, gritty red white and blue brush textures, Philly Phanatic in Phillies jersey pointing at camera and holding a sign, Philadelphia skyline and City Hall in background, Citizens Bank Park crowd, bold hand-painted typography, official sports event poster layout, high contrast, energetic, detailed, commercial poster design.', 'The "vintage-style" + "hand-painted typography" + "gritty brush textures" combination produces authentic sports-poster aesthetics. City-specific details (City Hall, Citizens Bank Park, Phanatic) localize the design. "Official sports event poster layout" triggers correct compositional conventions.', 'curated', NULL, NULL, ARRAY['poster','sports','baseball','vintage']::text[]),

-- #43 Restaurant Menu Card
('curated-mexican-menu-card', 'Mexican Restaurant Menu Card', 'UI Mockups', 'Design a modern restaurant menu', 'Design a modern Mexican restaurant menu. Include sections for Tacos, Burritos, and Drinks with realistic pricing. Use warm earthy tones, clean serif fonts, and a rustic background texture.', 'Short and effective — the cultural anchor (Mexican) + material cues (warm earthy tones, rustic texture) + typography direction (clean serif) give enough constraints for a convincing menu without over-specifying. Realistic pricing adds authenticity.', 'curated', NULL, NULL, ARRAY['ui','menu','restaurant','design']::text[]),

-- #44 Sketchnote Visual Summary
('curated-sketchnote-infographic', 'Sketchnote Visual Summary', 'Infographics', 'Create a hand-drawn sketchnote visual summary in graphic recording style', 'Create a hand-drawn sketchnote visual summary. Use a pristine white paper background (no lines). Art style: graphic recording / visual thinking using black ink fine-liners for clear outlines and text. Use colored markers (specifically teal, orange, and muted red) for simple shading and accents. Center the main title "AI STRATEGY 2026" in a 3D-style rectangular box. Surround the title with radially distributed simple doodles, business icons, stick figures, and graphs that explain the concepts. Use arrows to connect ideas. The text should be distinct, handwritten, all-caps printing, legible and organized like a professional brainstorming session. Layout should be A4.', 'The "graphic recording / visual thinking" style anchor is very specific — it triggers the conference-facilitation sketchnote aesthetic. Three-color constraint (teal, orange, muted red) on white prevents messy outputs. "All-caps printing" ensures legibility in the hand-drawn style.', 'curated', NULL, NULL, ARRAY['infographic','sketchnote','hand-drawn','business']::text[]),

-- #45 Founder Infographic Poster
('curated-founder-infographic', 'Tech Founder Infographic Poster', 'Posters', 'Create a scroll-stopping founder breakdown infographic poster', 'Vertical poster composition, portrait orientation, 4:5 (1080x1350). High-impact, scroll-stopping infographic poster of Jensen Huang. TOP 30% HOOK ZONE: Huge bold uppercase headline "THIS MAN BUILT THE AI ERA" in white + NVIDIA green, extremely large typography, high contrast, strong spacing. MIDDLE 40% HERO: Ultra-realistic portrait of Jensen Huang, chest-up, looking slightly upward, cinematic soft shadows, subtle rim light using NVIDIA green, soft glow behind subject, dark tech/editorial environment with subtle grid overlays. BOTTOM 30% INFO GRID: Glassmorphism cards with rounded corners and soft shadows. Mini bio: "Jensen Huang, Founder & CEO, NVIDIA — Built the backbone of the AI revolution." Timeline: 1993→NVIDIA founded, 2006→CUDA launches, 2012→Deep learning boom, 2023→AI era powered. Numbers: 80M+ developers, $3T+ valuation, 100+ countries. Quote: "The more you buy, the more you save." — Jensen Huang. Design: black/deep navy base, NVIDIA green accents, white typography, subtle glow, gradient lighting, thin grid overlays, bold modern sans-serif.', 'The three-zone layout (hook → hero → info grid) is optimized for mobile scrolling. Glassmorphism cards add modern depth. The specific data points (timeline, stats, quote) make it informational rather than just decorative. Brand color as accent throughout creates cohesion.', 'curated', NULL, NULL, ARRAY['poster','founder','infographic','tech']::text[]),

-- #46 AI Facial Aesthetics Report (Image Edit)
('curated-facial-aesthetics-report', 'AI Facial Aesthetics Upgrade Report', 'Image Edits', 'Generate a before/after facial aesthetic upgrade report from an uploaded photo', 'Generate a high-fidelity horizontal 4:3 "AI Facial Aesthetics Upgrade Report" based on the user''s uploaded frontal portrait photo. Strictly preserve identity, facial recognizability, core contours, age, skin texture, and temperament. Layout: horizontal "Central Before/After Dual-Face Main Visual + Surrounding Professional Annotations + Bottom Solution Matrix." Left: Before original facial state. Right: After facial aesthetics upgrade (Korean-style natural enhancement — fresh, upscale, Clean Beauty, natural subtle adjustment). Add numbered dots and thin arrow lines on After face labeling six areas: 01 Eyebrows (shape clarity, density, coordination), 02 Eyes (spirit, vitality, periorbital condition), 03 Nose (bridge, root, tip, alar relationship), 04 Facial Contour (cheekbones, jawline, chin proportions), 05 Lips & Mouth (shape, corners, refinement), 06 Skin Texture (tone evenness, luster, freshness). Bottom: Priority Matrix (Priority Improvements, Worth Trying, For Evaluation, High Caution categories). Visual style: high-end medical beauty consultation board + trendy magazine + professional analysis chart. Background: white/off-white/light gray with silver, gray-blue accents. Disclaimer: "This report is an evaluation and visual proposal, not a substitute for doctor''s consultation."', 'The six-area annotation system with numbered markers creates a professional diagnostic feel. The priority matrix at the bottom adds actionable hierarchy. The "Korean-style natural" direction prevents over-the-top results. Including a medical disclaimer adds credibility.', 'curated', NULL, NULL, ARRAY['image-edit','portrait','beauty','report']::text[]),

-- #47 Cutaway Educational Picture Book
('curated-cutaway-educational', 'Cutaway Educational Picture Book', 'Infographics', 'Create a cutaway educational illustration showing internal structure', 'Create a high-quality "Cutaway Educational Picture Book" illustration for the theme: Submarine. This combines cutaway display + internal structure explanation + functional zoning + picture book texture + information labeling. The viewer should simultaneously see external form, internal structure, hierarchical relationships, functional logic, and key knowledge points. Format: 3:4 vertical. Main subject centered, full use of vertical space. Through vertical extension, upper and lower layering, central main cutaway, and explanatory information distributed around. Requirements: themed object instantly recognizable with clear outline, internal structures clear and readable with hierarchy, key areas have functional/knowledge value, small figures and interactive scenes for fun, arrows/numbering/Chinese titles/explanation boxes included. Visual style: high-quality children''s science picture book balancing knowledge and approachability. Clear natural hand-drawn lines, bright gentle clean color palette, rich details without clutter, style between "children''s picture book illustration" and "explanatory diagram." Avoid: medical textbook atlases, cold industrial blueprints, toddler stick figures, ordinary posters without structure, cyberpunk heavy visuals, paper scan textures.', 'The "cutaway" instruction produces cross-section views that reveal internal complexity — submarines, buildings, human bodies all work well. Positioning between "picture book" and "explanatory diagram" is a precise aesthetic zone. The extensive "Avoid" list prevents common style drift.', 'curated', NULL, NULL, ARRAY['infographic','educational','cutaway','picture-book']::text[]),

-- #48 Design System Board (Japanese)
('curated-design-system-board', 'Japanese Design System Board', 'UI Mockups', 'Create a design system board for a Japanese web design studio', 'Create a premium design system board for a fictional Japanese web design studio. Theme: Playful Nordic-style design, Miyama Creative. One large smartphone mockup must be placed at the exact center as the main visual. Arrange desktop UI and design system modules around the phone. Include hero section, palette, typography, cards, buttons, inputs, icons, chips, and footer. Make it a polished Figma showcase board with rounded panels, clean spacing, elegant whitespace, modern Japanese taste, and readable Japanese labels. Do not make it a numbered spec sheet or plain grid. Aspect ratio 4:5.', 'The "smartphone at center + modules arranged around" composition creates a clear focal hierarchy. "Modern Japanese taste" as a style anchor produces clean, refined aesthetics. The "not a numbered spec sheet" constraint prevents dry documentation output and pushes toward polished presentation.', 'curated', NULL, NULL, ARRAY['ui','design-system','japanese','figma']::text[]),

-- #49 Japanese Lifestyle Magazine Annotations (Image Edit)
('curated-japanese-magazine-annotations', 'Japanese Lifestyle Magazine Annotations', 'Image Edits', 'Add stylish handwritten Japanese annotations to a photo like a lifestyle magazine', 'Analyze the uploaded photo and add stylish handwritten Japanese annotations like a Japanese lifestyle magazine. First, identify the main motif and treat it as the clear subject. At least 70-80% of annotations should relate directly to the main motif. Do not place comments on background elements unless they support the subject. Add a small headline, short side notes, tiny callouts, and one soft emotional phrase. Keep text short, natural, and human. Writing should feel emotive, tasteful, slightly poetic, and editorial. Use handwritten Japanese text with thin pen-like strokes and a stylish rough feel. Make text slightly larger and easy to read. Use dark text on bright areas and white/off-white text on dark areas. Keep layout elegant, balanced, not overcrowded. Use arrows, circles, underlines, or dotted marks when helpful. Output a single finished image with handwritten annotations already embedded.', 'The 70-80% focus rule prevents scattered annotations and maintains visual hierarchy. Adaptive text color (dark on bright, white on dark) ensures legibility. "Slightly poetic and editorial" tone direction produces the specific Japanese lifestyle magazine voice.', 'curated', NULL, NULL, ARRAY['image-edit','japanese','magazine','annotation']::text[]),

-- #50 Steampunk Constellation Anatomy Atlas
('curated-steampunk-constellation', 'Steampunk Constellation Anatomy Atlas', 'Posters', 'Create a steampunk-style constellation anatomy atlas poster', 'Steampunk Scientific Illustrator: Generate a retro steampunk-style constellation anatomy atlas poster for Sagittarius. Top title bar reads "Sagittarius Anatomy Atlas" / "ANATOMIA SAGITTARIUS" using a retro ribbon banner design. Background: aged parchment/yellowed old paper texture with natural stains and creases. Central subject: classic mythological archer figure with internal structure replaced by intricate gears, pipelines, metal skeletons, and steampunk elements. All icons in hand-drawn line art style with arrows/connecting lines showing logical relationships. Main color palette: warm brown, beige, antique bronze, with minimal high-contrast accent colors. Layout: left and right columns with central subject in middle. Left side: 3-5 functional modules (icons, titles, descriptions) + "Five-Layer Personality Structure" layered diagram. Right side: 3-5 trait modules + "Relationship Classification" and "Ecological Niche" sections. Bottom: "Advantages/Risks Comparison Table," "Survival Guide," and life philosophy declaration banner. Overall: rigorous, exquisite, retro mechanical aesthetics, clear readable text, 4K high definition.', 'The fusion of constellation mythology + steampunk mechanical internals + personality analysis creates a novel multi-layered concept. The structured layout (left modules, center figure, right modules, bottom table) ensures information density without chaos. Parchment texture + mechanical elements is a proven aesthetic pairing.', 'curated', NULL, NULL, ARRAY['poster','steampunk','constellation','anatomy']::text[])

ON CONFLICT (id) DO NOTHING;
