/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LaunchChecklistRouteImport } from './routes/launch-checklist'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CritiqueRouteImport } from './routes/critique'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ExamplesChar123IdChar125RouteImport } from './routes/examples.{-$id}'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiPublicGeneratePromptRouteImport } from './routes/api/public/generate-prompt'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchChecklistRoute = LaunchChecklistRouteImport.update({
  id: '/launch-checklist',
  path: '/launch-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CritiqueRoute = CritiqueRouteImport.update({
  id: '/critique',
  path: '/critique',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesChar123IdChar125Route =
  ExamplesChar123IdChar125RouteImport.update({
    id: '/examples/{-$id}',
    path: '/examples/{-$id}',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeneratePromptRoute = ApiPublicGeneratePromptRouteImport.update({
  id: '/api/public/generate-prompt',
  path: '/api/public/generate-prompt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/critique': typeof CritiqueRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/launch-checklist': typeof LaunchChecklistRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/examples/{-$id}': typeof ExamplesChar123IdChar125Route
  '/blog/': typeof BlogIndexRoute
  '/api/public/generate-prompt': typeof ApiPublicGeneratePromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/critique': typeof CritiqueRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/launch-checklist': typeof LaunchChecklistRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/examples/{-$id}': typeof ExamplesChar123IdChar125Route
  '/blog': typeof BlogIndexRoute
  '/api/public/generate-prompt': typeof ApiPublicGeneratePromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/critique': typeof CritiqueRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/launch-checklist': typeof LaunchChecklistRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/examples/{-$id}': typeof ExamplesChar123IdChar125Route
  '/blog/': typeof BlogIndexRoute
  '/api/public/generate-prompt': typeof ApiPublicGeneratePromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/critique'
    | '/gallery'
    | '/generate'
    | '/launch-checklist'
    | '/library'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/examples/{-$id}'
    | '/blog/'
    | '/api/public/generate-prompt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/critique'
    | '/gallery'
    | '/generate'
    | '/launch-checklist'
    | '/library'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/examples/{-$id}'
    | '/blog'
    | '/api/public/generate-prompt'
  id:
    | '__root__'
    | '/'
    | '/critique'
    | '/gallery'
    | '/generate'
    | '/launch-checklist'
    | '/library'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/examples/{-$id}'
    | '/blog/'
    | '/api/public/generate-prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CritiqueRoute: typeof CritiqueRoute
  GalleryRoute: typeof GalleryRoute
  GenerateRoute: typeof GenerateRoute
  LaunchChecklistRoute: typeof LaunchChecklistRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ExamplesChar123IdChar125Route: typeof ExamplesChar123IdChar125Route
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicGeneratePromptRoute: typeof ApiPublicGeneratePromptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-checklist': {
      id: '/launch-checklist'
      path: '/launch-checklist'
      fullPath: '/launch-checklist'
      preLoaderRoute: typeof LaunchChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critique': {
      id: '/critique'
      path: '/critique'
      fullPath: '/critique'
      preLoaderRoute: typeof CritiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/{-$id}': {
      id: '/examples/{-$id}'
      path: '/examples/{-$id}'
      fullPath: '/examples/{-$id}'
      preLoaderRoute: typeof ExamplesChar123IdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-prompt': {
      id: '/api/public/generate-prompt'
      path: '/api/public/generate-prompt'
      fullPath: '/api/public/generate-prompt'
      preLoaderRoute: typeof ApiPublicGeneratePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CritiqueRoute: CritiqueRoute,
  GalleryRoute: GalleryRoute,
  GenerateRoute: GenerateRoute,
  LaunchChecklistRoute: LaunchChecklistRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  ExamplesChar123IdChar125Route: ExamplesChar123IdChar125Route,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicGeneratePromptRoute: ApiPublicGeneratePromptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
